# Generated by Django 4.1 on 2022-09-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoSimApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tractoraction',
            name='users',
        ),
    ]
